CustomizableWeaponry:addFireSound("CW_KK_INS2_MP5K_FIRE", "weapons/mp5k/mp5k_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_MP5K_FIRE_SUPPRESSED", "weapons/mp5k/mp5k_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTBACK", "weapons/mp5k/handling/mp5k_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTLOCK", "weapons/mp5k/handling/mp5k_boltlock.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTRELEASE", "weapons/mp5k/handling/mp5k_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_EMPTY", "weapons/mp5k/handling/mp5k_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_FIRESELECT", "weapons/mp5k/handling/mp5k_fireselect.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGIN", "weapons/mp5k/handling/mp5k_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGOUT", "weapons/mp5k/handling/mp5k_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGRELEASE", "weapons/mp5k/handling/mp5k_magrelease.wav", 1, 100, CHAN_WEAPON)