CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK12_FIRE", "weapons/rpk12/rpk_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK_FIRE_SUPPRESSED", "weapons/rpk/rpk_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BIPODDEPLOY", "weapons/rpk/handling/rpk_bipoddeploy.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BIPODRETRACT", "weapons/rpk/handling/rpk_bipodretract.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BOLTBACK", "weapons/rpk/handling/rpk_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BOLTRELEASE", "weapons/rpk/handling/rpk_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_DEPLOYGROUNDHIT", "weapons/rpk/handling/rpk_deploygroundhit.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_EMPTY", "weapons/rpk/handling/rpk_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_ENDDEPLOYEDRELOAD", "weapons/rpk/handling/rpk_enddeployedreload.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_FETCHMAG", "weapons/rpk/handling/rpk_fetchmag.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_FIRESELECT", "weapons/rpk/handling/rpk_fireselect_1.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGIN", "weapons/rpk/handling/rpk_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGOUT", "weapons/rpk/handling/rpk_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGOUTRATTLE", "weapons/rpk/handling/rpk_magout_rattle.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGRELEASE", "weapons/rpk/handling/rpk_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_RATTLE", "weapons/rpk/handling/rpk_rattle.wav", 1, 100, CHAN_WEAPON)