CustomizableWeaponry:addFireSound("CW_KK_INS2_MINI14_FIRE2", "weapons/m9/m9_suppressed_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_MINI14_FIRE_SUPPRESSED", "weapons/mini14/mini14_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_BOLTBACK", "weapons/mini14/handling/mini14_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_BOLTRELEASE", "weapons/mini14/handling/mini14_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_EMPTY", "weapons/mini14/handling/mini14_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74M_FIRESELECT", "weapons/cw_kk_ins2_f_ak74/handling/ak74_fireselect_1.wav", "weapons/cw_kk_ins2_f_ak74/handling/ak74_fireselect_2.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_MAGIN", "weapons/mini14/handling/mini14_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_MAGOUT", "weapons/mini14/handling/mini14_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MINI14_MAGRELEASE", "weapons/mini14/handling/mini14_magrelease.wav", 1, 100, CHAN_WEAPON)
