CustomizableWeaponry:addFireSound("CW_KK_INS2_AK74_FIRE", "weapons/ak74/ak74_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_AK74_FIRE_SUPPRESSED", "weapons/ak74/ak74_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_BOLTBACK", "weapons/ak74/handling/ak74_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_BOLTRELEASE", "weapons/ak74/handling/ak74_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_EMPTY", "weapons/ak74/handling/ak74_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_FIRESELECT", "weapons/ak74/handling/ak74_fireselect_1.wav", "weapons/ak74/handling/ak74_fireselect_2.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_MAGIN", "weapons/ak74/handling/ak74_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_MAGOUT", "weapons/ak74/handling/ak74_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_MAGOUTRATTLE", "weapons/ak74/handling/ak74_magout_rattle.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_MAGRELEASE", "weapons/ak74/handling/ak74_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK74_RATTLE", "weapons/ak74/handling/ak74_rattle.wav", 1, 100, CHAN_WEAPON)