CustomizableWeaponry:addFireSound("CW_KK_INS2_M4A1_FIRE", "weapons/m4a1/m4a1_fp.wav", 1, 105, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_M4A1_FIRE_SUPPRESSED", "weapons/m4a1/m4a1_suppressed_fp.wav", 1, 75, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_BOLTBACK", "weapons/m4a1/handling/m4a1_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_BOLTRELEASE", "weapons/m4a1/handling/m4a1_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_EMPTY", "weapons/m4a1/handling/m4a1_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_FIRESELECT", "weapons/m4a1/handling/m4a1_fireselect.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_HIT", "weapons/m4a1/handling/m4a1_hit.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGHITRELEASE", "weapons/m4a1/handling/m4a1_maghitrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGIN", "weapons/m4a1/handling/m4a1_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGOUT", "weapons/m4a1/handling/m4a1_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGRELEASE", "weapons/m4a1/handling/m4a1_magrelease.wav", 1, 100, CHAN_WEAPON)
