CustomizableWeaponry:addFireSound("CW_KK_INS2_D_RPK_FIRE", "weapons/cw_kk_ins2_f_rpk/rpk_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_D_RPK_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_f_rpk/rpk_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_BIPODDEPLOY", "weapons/cw_kk_ins2_f_rpk/handling/rpk_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_BIPODRETRACT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_BOLTBACK", "weapons/cw_kk_ins2_f_rpk/handling/rpk_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_BOLTRELEASE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_DEPLOYGROUNDHIT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_EMPTY", "weapons/cw_kk_ins2_f_rpk/handling/rpk_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_ENDDEPLOYEDRELOAD", "weapons/cw_kk_ins2_f_rpk/handling/rpk_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_FETCHMAG", "weapons/cw_kk_ins2_f_rpk/handling/rpk_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_FIRESELECT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_MAGIN", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_MAGOUT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_MAGOUTRATTLE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_MAGRELEASE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_RPK_RATTLE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_rattle.wav")
