CustomizableWeaponry:addFireSound("CW_KK_INS2_AK105_FIRE", "weapons/cw_kk_ins2_f_ak74/ak74_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_AK105_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_f_ak74/ak74_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_BOLTBACK", "weapons/cw_kk_ins2_f_ak74/handling/ak74_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_BOLTRELEASE", "weapons/cw_kk_ins2_f_ak74/handling/ak74_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_EMPTY", "weapons/cw_kk_ins2_f_ak74/handling/ak74_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_FIRESELECT", "weapons/cw_kk_ins2_f_ak74/handling/ak74_fireselect_1.wav", "weapons/cw_kk_ins2_f_ak74/handling/ak74_fireselect_2.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_MAGIN", "weapons/cw_kk_ins2_f_ak74/handling/ak74_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_MAGOUT", "weapons/cw_kk_ins2_f_ak74/handling/ak74_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_MAGOUTRATTLE", "weapons/cw_kk_ins2_f_ak74/handling/ak74_magout_rattle.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_MAGRELEASE", "weapons/cw_kk_ins2_f_ak74/handling/ak74_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_AK105_RATTLE", "weapons/cw_kk_ins2_f_ak74/handling/ak74_rattle.wav", 1, 100, CHAN_WEAPON)
