CustomizableWeaponry:addFireSound("CW_KK_INS2_MP40_FIRE", "weapons/mp40/mp40_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_MP40_FIRE_SUPPRESSED", "weapons/mp40/mp40_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTBACK", "weapons/mp40/handling/mp40_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTLOCK", "weapons/mp40/handling/mp40_boltlock.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTUNLOCK", "weapons/mp40/handling/mp40_boltunlock.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_EMPTY", "weapons/mp40/handling/mp40_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_FIRESELECT", "weapons/mp5k/handling/mp5k_fireselect.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGHIT", "weapons/mp40/handling/mp40_maghit.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGIN", "weapons/mp40/handling/mp40_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGOUT", "weapons/mp40/handling/mp40_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGRELEASE", "weapons/mp40/handling/mp40_magrelease.wav", 1, 100, CHAN_WEAPON)