CustomizableWeaponry:addFireSound("CW_KK_INS2_D_AKS74U_FIRE", "weapons/cw_kk_ins2_f_aks74u/aks74u_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_D_AKS74U_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_f_aks74u/aks74u_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_BOLTBACK", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_BOLTRELEASE", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_EMPTY", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_FIRESELECT", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_fireselect_1.wav", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_fireselect_2.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_MAGIN", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_MAGOUT", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_MAGOUTRATTLE", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_magout_rattle.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_MAGRELEASE", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKS74U_RATTLE", "weapons/cw_kk_ins2_f_aks74u/handling/aks74u_rattle.wav", 1, 100, CHAN_WEAPON)
