CustomizableWeaponry:addFireSound("CW_KK_INS2_D_AKM_FIRE", "weapons/cw_kk_ins2_f_akm/akm_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_D_AKM_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_f_akm/akm_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_BOLTBACK", "weapons/cw_kk_ins2_f_akm/handling/akm_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_BOLTRELEASE", "weapons/cw_kk_ins2_f_akm/handling/akm_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_EMPTY", "weapons/cw_kk_ins2_f_akm/handling/akm_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_FIRESELECT", "weapons/cw_kk_ins2_f_akm/handling/akm_fireselect_1.wav", "weapons/cw_kk_ins2_f_akm/handling/akm_fireselect_2.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_MAGIN", "weapons/cw_kk_ins2_f_akm/handling/akm_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_MAGOUT", "weapons/cw_kk_ins2_f_akm/handling/akm_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_MAGOUTRATTLE", "weapons/cw_kk_ins2_f_akm/handling/akm_magout_rattle.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_MAGRELEASE", "weapons/cw_kk_ins2_f_akm/handling/akm_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D_AKM_RATTLE", "weapons/cw_kk_ins2_f_akm/handling/akm_rattle.wav", 1, 100, CHAN_WEAPON)
