CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK74M_FIRE", "weapons/cw_kk_ins2_f_rpk/rpk_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK74M_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_f_rpk/rpk_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BIPODDEPLOY", "weapons/cw_kk_ins2_f_rpk/handling/rpk_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BIPODRETRACT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BOLTBACK", "weapons/cw_kk_ins2_f_rpk/handling/rpk_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BOLTRELEASE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_DEPLOYGROUNDHIT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_EMPTY", "weapons/cw_kk_ins2_f_rpk/handling/rpk_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_ENDDEPLOYEDRELOAD", "weapons/cw_kk_ins2_f_rpk/handling/rpk_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_FETCHMAG", "weapons/cw_kk_ins2_f_rpk/handling/rpk_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_FIRESELECT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGIN", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGOUT", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGOUTRATTLE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGRELEASE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_RATTLE", "weapons/cw_kk_ins2_f_rpk/handling/rpk_rattle.wav")
