CustomizableWeaponry:addFireSound("CW_KK_INS2_GYURZA_FIRE", "weapons/gyurza/makarov_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_GYURZA_FIRE_SUPPRESSED", "weapons/gyurza/makarov_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_BOLTBACK", "weapons/makarov/handling/makarov_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_BOLTRELEASE", "weapons/makarov/handling/makarov_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_EMPTY", "weapons/makarov/handling/makarov_empty.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GYURZA_MAGHIT", "weapons/gyurza/handling/makarov_maghit.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GYURZA_MAGIN", "weapons/gyurza/handling/makarov_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GYURZA_MAGOUT", "weapons/gyurza/handling/makarov_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GYURZA_MAGRELEASE", "weapons/gyurza/handling/makarov_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_SAFETY", "weapons/makarov/handling/makarov_safety.wav", 1, 100, CHAN_WEAPON)