CustomizableWeaponry:addFireSound("CW_KK_INS2_T5000_FIRE", "weapons/new_sr/t5000_fp.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addFireSound("CW_KK_INS2_T5000_FIRE_SUPPRESSED", "weapons/new_sr/t5000_suppressed_fp.wav", 1, 70, CHAN_WEAPON)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_BOLTBACK", "weapons/new_sr/handling/new_sr_boltback.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_BOLTFORWARD", "weapons/new_sr/handling/new_sr_boltforward.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_BOLTLATCH", "weapons/new_sr/handling/new_sr_boltlatch.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_BOLTRELEASE", "weapons/new_sr/handling/new_sr_boltrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_MAGRELEASE", "weapons/new_sr/handling/new_sr_magrelease.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_MAGIN", "weapons/new_sr/handling/new_sr_magin.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_MAGHIT", "weapons/new_sr/handling/new_sr_maghit.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NEWSR_MAGOUT", "weapons/new_sr/handling/new_sr_magout.wav", 1, 100, CHAN_WEAPON)
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MOSIN_EMPTY", "weapons/mosin/handling/mosin_empty.wav", 1, 100, CHAN_WEAPON)